# Generated by Django 4.1 on 2022-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_image_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
