# Generated by Django 4.1 on 2022-09-08 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('gender', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('contact', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=50000)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=50000)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('retailer_sku', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('url', models.URLField()),
                ('color', models.CharField(max_length=122)),
                ('currency', models.CharField(max_length=122)),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('care', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('image_urls', models.TextField()),
                ('skus', models.TextField()),
            ],
        ),
    ]
